security:
  jwt:
    key: ${JWT_KEY}

spring:
  profiles:
    include=default:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/nostalogic?currentSchema=nostalogic_access
  jpa:
    show-sql: false
  liquibase:
    default-schema: nostalogic_access

microservices:
  api-url: https://nostalogic.io
  api-access-url: ${API_ACCESS_URL}
  api-excomm-url: ${API_EXCOMM_URL}
  access-port:
  user-port:
  excomm-port:
  content-port:
  file-port:

client:
  base-url: https://nostalogic.net
  port:
