security:
  jwt:
    key: ZqHPJkeRMjYRpNKFfFtUNZZPGnHzclYFpwnISiabFCddietCFUeiKBTNyMaLOsgQ
    duration-minutes: 525600

spring:
  application:
    name: access-service-test
  datasource:
    username: postgres
    password: solice
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nostalogic?currentSchema=test_nostalogic_access
    platform: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: test_nostalogic_access


server:
  port: 3601

microservices:
  base-url: http://localhost
  access-port: :3601

client:
  base-url: http://localhost
  port: :4200
