
spring:
  application:
    name: access-service-test
  datasource:
    username: postgres
    password: solice
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nostalogic?currentSchema=test_nostalogic_access
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: test_nostalogic_access
  sql:
    init:
      platform: postgres


server:
  port: 3601

microservices:
  api-url: http://localhost
  api-access-url: http://localhost
  api-excomm-url: http://localhost
  access-port:

client:
  base-url: http://localhost
  port: :4200
