security:
  jwt:
    key: ZqHPJkeRMjYRpNKFfFtUNZZPGnHzclYFpwnISiabFCddietCFUeiKBTNyMaLOsgQ
    duration-minutes: 525600

spring:
  application:
    name: access-service
  datasource:
    username: postgres
    password: solice
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nostalogic?currentSchema=nostalogic_access
    platform: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: nostalogic_access


server:
  port: 3601

microservices:
  access:
    base-url: http://localhost:3601
